module Gtk
  # This is a convenience function for showing an application’s about box. The constructed dialog is associated with
  # the parent window and NOT reused for future invocations of this function.
  def show_about_dialog(parent : Window?, *, artists : Enumerable(::String)? = nil,
                        authors : Enumerable(::String)? = nil,
                        comments : ::String? = nil,
                        copyright : ::String? = nil,
                        documenters : Enumerable(::String)? = nil,
                        license : ::String? = nil,
                        license_type : Gtk::License? = nil,
                        logo : Gdk::Paintable? = nil,
                        logo_icon_name : ::String? = nil,
                        program_name : ::String? = nil,
                        system_information : ::String? = nil,
                        translator_credits : ::String? = nil,
                        version : ::String? = nil,
                        website : ::String? = nil,
                        website_label : ::String? = nil,
                        wrap_license : Bool? = nil,
                        application : Gtk::Application? = nil,
                        child : Gtk::Widget? = nil,
                        decorated : Bool? = nil,
                        default_height : Int32? = nil,
                        default_widget : Gtk::Widget? = nil,
                        default_width : Int32? = nil,
                        deletable : Bool? = nil,
                        display : Gdk::Display? = nil,
                        focus_visible : Bool? = nil,
                        focus_widget : Gtk::Widget? = nil,
                        fullscreened : Bool? = nil,
                        handle_menubar_accel : Bool? = nil,
                        hide_on_close : Bool? = nil,
                        icon_name : ::String? = nil,
                        is_active : Bool? = nil,
                        maximized : Bool? = nil,
                        mnemonics_visible : Bool? = nil,
                        resizable : Bool? = nil,
                        startup_id : ::String? = nil,
                        title : ::String? = nil,
                        can_focus : Bool? = nil,
                        can_target : Bool? = nil,
                        css_classes : Enumerable(::String)? = nil,
                        css_name : ::String? = nil,
                        cursor : Gdk::Cursor? = nil,
                        focus_on_click : Bool? = nil,
                        focusable : Bool? = nil,
                        halign : Gtk::Align? = nil,
                        has_default : Bool? = nil,
                        has_focus : Bool? = nil,
                        has_tooltip : Bool? = nil,
                        height_request : Int32? = nil,
                        hexpand : Bool? = nil,
                        hexpand_set : Bool? = nil,
                        layout_manager : Gtk::LayoutManager? = nil,
                        margin_bottom : Int32? = nil,
                        margin_end : Int32? = nil,
                        margin_start : Int32? = nil,
                        margin_top : Int32? = nil,
                        name : ::String? = nil,
                        opacity : Float64? = nil,
                        overflow : Gtk::Overflow? = nil,
                        receives_default : Bool? = nil,
                        root : Gtk::Root? = nil,
                        scale_factor : Int32? = nil,
                        sensitive : Bool? = nil,
                        tooltip_markup : ::String? = nil,
                        tooltip_text : ::String? = nil,
                        valign : Gtk::Align? = nil,
                        vexpand : Bool? = nil,
                        vexpand_set : Bool? = nil,
                        visible : Bool? = nil,
                        width_request : Int32? = nil)
    dialog = AboutDialog.new(artists: artists, authors: authors, comments: comments, copyright: copyright, documenters: documenters,
      license: license, license_type: license_type, logo: logo, logo_icon_name: logo_icon_name, program_name: program_name,
      system_information: system_information, translator_credits: translator_credits, version: version, website: website,
      website_label: website_label, wrap_license: wrap_license, application: application, child: child, decorated: decorated,
      default_height: default_height, default_widget: default_widget, default_width: default_width, deletable: deletable,
      destroy_with_parent: true, display: display, focus_visible: focus_visible, focus_widget: focus_widget,
      fullscreened: fullscreened, handle_menubar_accel: handle_menubar_accel, hide_on_close: hide_on_close,
      icon_name: icon_name, is_active: is_active, maximized: maximized, mnemonics_visible: mnemonics_visible, modal: true,
      resizable: resizable, startup_id: startup_id, title: title, transient_for: parent, can_focus: can_focus,
      can_target: can_target, css_classes: css_classes, css_name: css_name, cursor: cursor, focus_on_click: focus_on_click,
      focusable: focusable, halign: halign, has_default: has_default, has_focus: has_focus, has_tooltip: has_tooltip,
      height_request: height_request, hexpand: hexpand, hexpand_set: hexpand_set, layout_manager: layout_manager,
      margin_bottom: margin_bottom, margin_end: margin_end, margin_start: margin_start, margin_top: margin_top, name: name,
      opacity: opacity, overflow: overflow, receives_default: receives_default, root: root,
      scale_factor: scale_factor, sensitive: sensitive, tooltip_markup: tooltip_markup, tooltip_text: tooltip_text,
      valign: valign, vexpand: vexpand, vexpand_set: vexpand_set, visible: visible, width_request: width_request)
    dialog.close_request_signal.connect do
      dialog.destroy
      true
    end
    dialog.present
  end
end
